### PR TITLE
fix sdio and pcie build for kernel 6.7

### PR DESCRIPTION
**Pull request by amazingfate**
Commit https://github.com/radxa-pkg/aic8800/commit/c709f6505715c6e5734cc6a928ea8a63f4907f3b only fixes build for usb, and here is the fix for sdio and pcie.
@andyshrk

### CODE REVIEW

**Comment by amazingfate** [comment]
I can't build deb on my system because there is a binary file `debian/patches/fmacfw_8800d80_u02.bin`. I will test debs built by github workflow with kernel 6.10-rc4.

**Review by RadxaYuntian — APPROVED** [review]

**Comment by RadxaYuntian** [comment]
Waiting for self-report.
@CodeChenL might be related.

**Comment by amazingfate** [comment]
sdio dkms is installed fine. While pcie package build with error. Add two more fixes for pcie.

**Comment by CodeChenL** [comment]
The 6.1 compilation reports errors that don't appear to be related to this PR. This is my PR https://github.com/radxa-pkg/aic8800/pull/18

**Comment by amazingfate** [comment]
Now all the 3 dkms packages are installed fine with kernel 6.10-rc4.

**Review by RadxaYuntian — APPROVED** [review]

**Review by RadxaYuntian — APPROVED** [review]

**Comment by andyshrk** [comment]
Thanks for the cool job。

Do I need to wait until this repo generate a new release to verify it on armbian build system ？

**Comment by RadxaYuntian** [comment]
Yes because it is using the latest release from this repo. We have a few more build issues that need to be fixed before creating a new release.

**Comment by andyshrk** [comment]
It seems that we are missing the SDIO firmware：

[    6.261408] AICWFDBG(LOGINFO)        aicwf_sdio_chipmatch USE AIC8801
[    6.261410] aicbsp: aicbsp_get_feature, set FEATURE_SDIO_CLOCK 50 MHz
[    6.261412] aicbsp: aicwf_sdio_reg_init
[    6.261562] aicbsp: Set SDIO Clock 50 MHz
[    6.263562] AICWFDBG(LOGINFO)        aicbsp: aicbsp_driver_fw_init, chip rev: 7
[    6.263572] rwnx_load_firmware :firmware path = /lib/firmware/aic8800_fw/SDIO/aic8800D80/fw_patch_table_u03.bin  
[    6.292395] rwnx_load_firmware: fw_patch_table_u03.bin file failed to open
[    6.560067] rwnx_load_firmware :firmware path = /lib/firmware/aic8800_fw/SDIO/aic8800D80/fw_adid_u03.bin  
[    6.560091] rwnx_load_firmware: fw_adid_u03.bin file failed to open
[    6.560096] wrong size of firmware file
[    6.198627] rwnx_plat_bin_fw_upload_android
[    6.198635] rwnx_load_firmware :firmware path = /lib/firmware/aic8800_fw/SDIO/aic8800D80/fw_patch_u03.bin  
[    6.198662] rwnx_load_firmware: fw_patch_u03.bin file failed to open
[    6.129660] aicbsp: bt patch version: - Sep 06 2022 18:21:39 - git 17b24d4
[    6.129690] rwnx_plat_bin_fw_upload_android
[    6.129694] rwnx_load_firmware :firmware path = /lib/firmware/aic8800_fw/SDIO/aic8800D80/fmacfw.bin  
[    6.129716] rwnx_load_firmware: fmacfw.bin file failed to open
[    6.129718] wrong size of firmware file
[    6.129720] download wifi fw fail
[    6.129761] aicbsp: aicbsp_sdio_remove
[    6.129764] aicbsp: aicwf_sdio_release
[    6.129793] aicbsp: aicwf_bus_deinit
[    6.129795] aicbsp: aicwf_sdio_bus_stop
[    6.129801] aicbsp: sdio_err:<aicwf_sdio_bustx_thread,1339>: sdio bustx thread stop
[    6.129821] aicbsp: sdio_err:<aicwf_sdio_busrx_thread,1358>: sdio busrx thread stop

**Comment by CodeChenL** [comment]
> It seems that we are missing the SDIO firmware：
> 
> [ 6.261408] AICWFDBG(LOGINFO) aicwf_sdio_chipmatch USE AIC8801 [ 6.261410] aicbsp: aicbsp_get_feature, set FEATURE_SDIO_CLOCK 50 MHz [ 6.261412] aicbsp: aicwf_sdio_reg_init [ 6.261562] aicbsp: Set SDIO Clock 50 MHz [ 6.263562] AICWFDBG(LOGINFO) aicbsp: aicbsp_driver_fw_init, chip rev: 7 [ 6.263572] rwnx_load_firmware :firmware path = /lib/firmware/aic8800_fw/SDIO/aic8800D80/fw_patch_table_u03.bin [ 6.292395] rwnx_load_firmware: fw_patch_table_u03.bin file failed to open [ 6.560067] rwnx_load_firmware :firmware path = /lib/firmware/aic8800_fw/SDIO/aic8800D80/fw_adid_u03.bin [ 6.560091] rwnx_load_firmware: fw_adid_u03.bin file failed to open [ 6.560096] wrong size of firmware file [ 6.198627] rwnx_plat_bin_fw_upload_android [ 6.198635] rwnx_load_firmware :firmware path = /lib/firmware/aic8800_fw/SDIO/aic8800D80/fw_patch_u03.bin [ 6.198662] rwnx_load_firmware: fw_patch_u03.bin file failed to open [ 6.129660] aicbsp: bt patch version: - Sep 06 2022 18:21:39 - git 17b24d4 [ 6.129690] rwnx_plat_bin_fw_upload_android [ 6.129694] rwnx_load_firmware :firmware path = /lib/firmware/aic8800_fw/SDIO/aic8800D80/fmacfw.bin [ 6.129716] rwnx_load_firmware: fmacfw.bin file failed to open [ 6.129718] wrong size of firmware file [ 6.129720] download wifi fw fail [ 6.129761] aicbsp: aicbsp_sdio_remove [ 6.129764] aicbsp: aicwf_sdio_release [ 6.129793] aicbsp: aicwf_bus_deinit [ 6.129795] aicbsp: aicwf_sdio_bus_stop [ 6.129801] aicbsp: sdio_err:<aicwf_sdio_bustx_thread,1339>: sdio bustx thread stop [ 6.129821] aicbsp: sdio_err:<aicwf_sdio_busrx_thread,1358>: sdio busrx thread stop

@RadxaYuntian Our released aic8800-firmware only has the u02 version of the firmware; it looks like we need to update the firmware.

**Comment by CodeChenL** [comment]
> It seems that we are missing the SDIO firmware：
> 
> [ 6.261408] AICWFDBG(LOGINFO) aicwf_sdio_chipmatch USE AIC8801 [ 6.261410] aicbsp: aicbsp_get_feature, set FEATURE_SDIO_CLOCK 50 MHz [ 6.261412] aicbsp: aicwf_sdio_reg_init [ 6.261562] aicbsp: Set SDIO Clock 50 MHz [ 6.263562] AICWFDBG(LOGINFO) aicbsp: aicbsp_driver_fw_init, chip rev: 7 [ 6.263572] rwnx_load_firmware :firmware path = /lib/firmware/aic8800_fw/SDIO/aic8800D80/fw_patch_table_u03.bin [ 6.292395] rwnx_load_firmware: fw_patch_table_u03.bin file failed to open [ 6.560067] rwnx_load_firmware :firmware path = /lib/firmware/aic8800_fw/SDIO/aic8800D80/fw_adid_u03.bin [ 6.560091] rwnx_load_firmware: fw_adid_u03.bin file failed to open [ 6.560096] wrong size of firmware file [ 6.198627] rwnx_plat_bin_fw_upload_android [ 6.198635] rwnx_load_firmware :firmware path = /lib/firmware/aic8800_fw/SDIO/aic8800D80/fw_patch_u03.bin [ 6.198662] rwnx_load_firmware: fw_patch_u03.bin file failed to open [ 6.129660] aicbsp: bt patch version: - Sep 06 2022 18:21:39 - git 17b24d4 [ 6.129690] rwnx_plat_bin_fw_upload_android [ 6.129694] rwnx_load_firmware :firmware path = /lib/firmware/aic8800_fw/SDIO/aic8800D80/fmacfw.bin [ 6.129716] rwnx_load_firmware: fmacfw.bin file failed to open [ 6.129718] wrong size of firmware file [ 6.129720] download wifi fw fail [ 6.129761] aicbsp: aicbsp_sdio_remove [ 6.129764] aicbsp: aicwf_sdio_release [ 6.129793] aicbsp: aicwf_bus_deinit [ 6.129795] aicbsp: aicwf_sdio_bus_stop [ 6.129801] aicbsp: sdio_err:<aicwf_sdio_bustx_thread,1339>: sdio bustx thread stop [ 6.129821] aicbsp: sdio_err:<aicwf_sdio_busrx_thread,1358>: sdio busrx thread stop

Then latest [released](https://github.com/radxa-pkg/aic8800/releases/tag/3.0%2Bgit20240327.3561b08f-2) is works fine on rock 3c 5.10 and rock 5c 6.1

**Comment by andyshrk** [comment]
> > It seems that we are missing the SDIO firmware：
> > [ 6.261408] AICWFDBG(LOGINFO) aicwf_sdio_chipmatch USE AIC8801 [ 6.261410] aicbsp: aicbsp_get_feature, set FEATURE_SDIO_CLOCK 50 MHz [ 6.261412] aicbsp: aicwf_sdio_reg_init [ 6.261562] aicbsp: Set SDIO Clock 50 MHz [ 6.263562] AICWFDBG(LOGINFO) aicbsp: aicbsp_driver_fw_init, chip rev: 7 [ 6.263572] rwnx_load_firmware :firmware path = /lib/firmware/aic8800_fw/SDIO/aic8800D80/fw_patch_table_u03.bin [ 6.292395] rwnx_load_firmware: fw_patch_table_u03.bin file failed to open [ 6.560067] rwnx_load_firmware :firmware path = /lib/firmware/aic8800_fw/SDIO/aic8800D80/fw_adid_u03.bin [ 6.560091] rwnx_load_firmware: fw_adid_u03.bin file failed to open [ 6.560096] wrong size of firmware file [ 6.198627] rwnx_plat_bin_fw_upload_android [ 6.198635] rwnx_load_firmware :firmware path = /lib/firmware/aic8800_fw/SDIO/aic8800D80/fw_patch_u03.bin [ 6.198662] rwnx_load_firmware: fw_patch_u03.bin file failed to open [ 6.129660] aicbsp: bt patch version: - Sep 06 2022 18:21:39 - git 17b24d4 [ 6.129690] rwnx_plat_bin_fw_upload_android [ 6.129694] rwnx_load_firmware :firmware path = /lib/firmware/aic8800_fw/SDIO/aic8800D80/fmacfw.bin [ 6.129716] rwnx_load_firmware: fmacfw.bin file failed to open [ 6.129718] wrong size of firmware file [ 6.129720] download wifi fw fail [ 6.129761] aicbsp: aicbsp_sdio_remove [ 6.129764] aicbsp: aicwf_sdio_release [ 6.129793] aicbsp: aicwf_bus_deinit [ 6.129795] aicbsp: aicwf_sdio_bus_stop [ 6.129801] aicbsp: sdio_err:<aicwf_sdio_bustx_thread,1339>: sdio bustx thread stop [ 6.129821] aicbsp: sdio_err:<aicwf_sdio_busrx_thread,1358>: sdio busrx thread stop
> 
> Then latest [released](https://github.com/radxa-pkg/aic8800/releases/tag/3.0%2Bgit20240327.3561b08f-2) is works fine on rock 3c 5.10 and rock 5c 6.1

I think rock 3c and rock 5c are use usb for aix8800 ？ My test case is a sdio drivered mode。

**Comment by RadxaYuntian** [comment]
3C uses SDIO. We are also only checking for our supported kernels for now.

**Comment by andyshrk** [comment]
> 3C uses SDIO. We are also only checking for our supported kernels for now.

Maybe 3C also has the issue if it runs with armbian edge kernel。

Would you please share the kernel dmesg with this aic8800 work of Linux 6.1 on 3C ？

**Pull request merged**
